artifact_location: file:///home/David/Documents/GithubRepos/news-trend-analysis/mlflow_tracking/357816244660041017
creation_time: 1761838077181
experiment_id: '357816244660041017'
last_update_time: 1761838077181
lifecycle_stage: active
name: news-trend-analysis
